export const filterSearch = {
    FILTER_BY_ALL_USERS: "FILTER_BY_ALL_USERS",
    FILTER_BY_MALE_USERS: "FILTER_BY_MALE_USERS",
    FILTER_BY_FEMALE_USERS: "FILTER_BY_FEMALE_USERS",

}

export const searchCriteria = {
    SEARCH_BY_NAME: "SEARCH_BY_NAME",
    SEARCH_BY_EMAIL: "SEARCH_BY_EMAIL",
    SEARCH_BY_COUNTRY: "SEARCH_BY_COUNTRY",
}
